### ISSUE TITLE
preseed de jessie pregunta de firmware

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/live-cd#1]
corregir el preseed en el branch testing para contestas las preguntas
1) el idioma no esta completo . Deseo continuar? => SI
2) cargar firmwares de medios externos => NO

**Comment by lvm** [comment]
Revisar commit y reabrir en caso de que haga falta.

**Comment by ftoledo** [comment]
mauro, lo vuelvo abrir porque en el ultimo build no tomo el cambios. hay que verificar porque no funciona.

**Comment by ftoledo** [comment]
sirve? http://ubuntuforums.org/showthread.php?t=2029774

**Comment by ftoledo** [comment]
chau d-i, hola calamares
