### ISSUE TITLE
Secret Maryo Chronicles: tiene resolución mayor a la pantalla

### ISSUE THREAD

**Issue by AgataGuma** [HuayraLinux/live-cd#11]
Se abre a pantalla completa y no se visualiza bien.

**Comment by ftoledo** [comment]
Eso sucede en las noteboos con CedarTrail que tiene problemas con el driver de video.
De todas maneras, se cambio SMC por SuperTux.

**Comment by mckaygerhard** [comment]
errr el issue es para ver que se puede hacer no para quitarlo y cambiarlo... !!!! mas o menos no entendi! Se supone que se tiene que buscar uan solcuon como poner por defecto en el SMC 640x480 lo cual se puede.. que decepcion!
