### ISSUE TITLE
No permite instalar paquetes .deb haciendo doble click

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/live-cd#13]
En la nueva imagen, cuando se hace doble click sobre un paquete .deb se abre el descompresor de archivos de gnome. 

Pienso que lo ideal sería que abra el instalador de paquetes, que está instalado en el sistema pero no está asociado a los .deb por omisión.

![huayra 4 0b running 2016-09-26 11-24-22](https://cloud.githubusercontent.com/assets/99183/18837890/dab9cb80-83db-11e6-8f70-64f2d4884af4.png)

**Comment by ftoledo** [comment]
corregido en huayra-desktop-4.0.11
