### ISSUE TITLE
Minimizar y lista de ventanas poco accesible ...

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/live-cd#14]
Tal vez no esté comprendiendo gnome, así que pido disculpas por adelantado... pero al probar el escritorio nuevo no me queda claro qué aplicaciones están abiertas... y alt+tab o un gesto touch no me parece muy accesible para usuarios nuevos (¡es tan windows 8!)

¿Existe alguna forma de incluir la lista de ventanas en el panel?, ¿o un botón para listar las aplicaciones abiertas?. ¿o es una pavada lo que pregunto 🙈 ?

**Comment by ftoledo** [comment]
Con la tecla **Win** o Arrastrado el puntero del mouse a la esquina superior izquierda te muestra las ventanas minimizadas.

![gnome_shell](https://cloud.githubusercontent.com/assets/95441/18841466/3d693e6c-83e8-11e6-95f4-442d75080bff.png)
