### ISSUE TITLE
Faltan los fondos de pantalla personalizados de huayra

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/live-cd#16]
Cuando se quiere cambiar el fondo de pantalla solo aparecen disponibles los fondos de gnome, no se ven los fondos personalizados de huayra:

![huayra 4 0b running 2016-09-26 12-22-37](https://cloud.githubusercontent.com/assets/99183/18840147/fa649d86-83e3-11e6-9993-f0701f0fb011.png)

**Comment by ftoledo** [comment]
Ccorregido en hayra-desktop-4.0.9 (se agregó por ahora el huayra-backgrounds-pixelarte)
