### ISSUE TITLE
Actualizar huayra-ritmos a la versión 0.9.9 y huayra-ritmos-extra a 0.0.4

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/live-cd#17]
Hicimos varios arreglos que surgieron del testing que hicimos con @iglosiggio y @santiagoarmas. La versión que se debería incluir en huayra 4 es la última que está en torbellino:
- huayra-ritmos 0.9.9
- huayra-ritmos-data 0.9.9
- huayra-ritmos-extra 0.0.4

**Comment by ftoledo** [comment]
Listo.
