### ISSUE TITLE
the x86 flavour boot into uefi devices?

### ISSUE THREAD

**Issue by mckaygerhard** [HuayraLinux/live-cd#20]
aqui he notado hablan español asi que me deshago del odioso "inglish"!

veo en el repositorio git archivos para el arrranque EFI, quisiera saber si sirve el arranque x86 con EFI y como hicieron para activarla en un live process

**Comment by ftoledo** [comment]
hola @mckaygerhard. Estos archivos son ahora obsoletos y en breve se van a sacar. Antes agregamos de forma manual el soporte de efi en la iso. Ahora, la herramienta live-build tiene mejor soporte y no hacen falta.

Con respecto a la arquitectura, si bien estamos trabajando sobre amd64, se puede hacer sin problemas una version para x86, en el directorio /boot de la iso generada (no del respositorio) live-build ya agrega el archivo bootia32.efi para arracar desde un efi de 32bits.

**Comment by mckaygerhard** [comment]
umm el primer parrafo se parece al la respuesta del issue #11 pero ablandada por el segundo parrafo.. 

veras.. y espero tomes en cuenta esto: **no todos los hardware funcionan con "la mode de lo ultimo" y ademas para completar, no todo el mundo tiene para tener mucha ram ni equipos modernos**

particulamente este caso: en mucho paises no es muy gracioso darle un equipo de 1200$ (enpromedio) para que lo tengan en el bolso escolar y lo llevan a la escuela porque no todos los paises son seguros.. 
pero pero, sin embargo es mucho mas las cantidad de paises con niños inteligentes que quieren aportar y hacer algo util.. y no basura de moda, pero estos no tienen esos recursos, por ende necesitan un lnux que instale.. 

si aqui en este punto vienes a decir "esta alpine linux" equivocado.. en uan de las donaciones esta la Zoran Framegrabeer el cual su soporte fue removido en el kernel 2.6.18, el cual afortunadamente el rethad soporto muchos anios y aun se pudo instalar en equipos hasta el 2016... y en el los niños al crecer notaron que realmente al tener menos lineas de codigo y deciciones logicas ejecutaba mucho mas rapido...

**en conclusion pregunto por como hacian antes.. para lograr arrancar el live en equipos con UEFI.. quizas con con secureboot pero si con UEFI** ya que hay muchas donaciones en el mundo de la famosa "magagianes" o la mal llmada "canaimita" el cual es muy buen equipo (menos la ultima generacion) pero que ningun linux moderno sirve ni la distro de uds.. espero haber sido claro y si lo tomas en cuenta servira para mayores colaboradores ya que veo que es un equipo de "pocos" (todos lo issues son tuyos?) pero tomandome en cuenta seria un equipo de "muchos" con benefici mutuo..

**Comment by ftoledo** [comment]
Creo que se entendió mal la respuesta.

No hablo de hardware obsoleto, sino del metodo para tener soporte de uefi en la iso, que es obsoleto. Porque la herramienta live-buid ya lo hace. En versiones anteriores no lo hacía, entonces agregabamos manualmente los archivos de uefi en /boot

https://github.com/HuayraLinux/live-cd/commit/d282eb00061c5cf5c2ef794d60648a19833bfbcc

Ahora live-build ya tiene muchos parches para tener mejor soporte de efi: 
https://salsa.debian.org/live-team/live-build/commits/master?utf8=%E2%9C%93&search=efi

**Comment by mckaygerhard** [comment]
ah ya vi la commit del maunal.. @ftoledo eso era lo que yo queria .. gracias por el commit especifico..  y si el live-boot ya lo hace incluso con versiones viejas.. intentare.. .. cualquier cosa aunque ya esta cerrado colocare notas aqui si son necesarias..

**Comment by mckaygerhard** [comment]
tal como prometi.. una acotacion o nota sobre usar live-build pero haciendo imagenes viejas: https://t.me/s/vegnuli/371 el error y su solicuion cuando aparece que no encuentra el paquete isolinux
