### ISSUE TITLE
Prompt de red

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/live-cd#21]
Desde pendrive en hardware real modo UEFI, le dí instalar y en la detección de HW no detecta placa de red.  en modo LIVE, SI. anda ok

**Comment by matiasdelellis** [comment]
@ftoledo 
Esto me parece que en realiad es falta de firmware (Dup de #1). Ahi le pregunte a @DiegoAccorinti 

Pero el parche que habia hecho mauro esta mal.. 

https://github.com/HuayraLinux/live-cd/blob/huayra-4/config/includes.installer/preseed.cfg#L83

Deberia ser:
```
-- ethdetect ethdetect/prompt-missing-firmware boolean false
++ d-i ethdetect/prompt_missing_firmware boolean false
```

Ante la duda....
https://github.com/search?q=prompt-missing-firmware&type=code

vs. 

https://github.com/search?q=prompt_missing_firmware&type=code

:sweat_smile:

**Comment by ftoledo** [comment]
El tema es que me parece que no es la pregunta de missing firmware, sino de que no detecta un dispositivo de red, la de missing firmware es cuando te dice si queres cargar firmware desde un usb externo.. y esa no aparece por lo tanto esta ok. 
yo creo que d-i netcfg/enable boolean false deberia hacer eso, pero seguramente haya cambiado

**Comment by ftoledo** [comment]
https://www.debian.org/releases/buster/example-preseed.txt

```
# netcfg will choose an interface that has link if possible. This makes it
# skip displaying a list if there is more than one interface.
d-i netcfg/choose_interface select auto

# To pick a particular interface instead:
#d-i netcfg/choose_interface select eth1
```

**Comment by matiasdelellis** [comment]
Ok..
![imagen](https://user-images.githubusercontent.com/733715/107799062-b6a9a000-6d3b-11eb-9380-2e368f22b693.png)

**Comment by matiasdelellis** [comment]
EN definitiva supongo que es:

`d-i netcfg/enable boolean false`

**Comment by ftoledo** [comment]
> EN definitiva supongo que es:
> 
> `d-i netcfg/enable boolean false`

esa ya estaba la que agregue es d-i netcfg/choose_interface select auto

**Comment by matiasdelellis** [comment]
`ethdetect	ethdetect/module_select	select	no ethernet card`

**Comment by matiasdelellis** [comment]
> `ethdetect ethdetect/module_select select no ethernet card`

Listo.. con eso anduvo..
Mismo link de descarga para probar...
 * http://ci-huayra.conectarigualdad.gob.ar/build/5/huayra-amd64-5.0b.iso

Comprueben y cierren...

**Comment by ftoledo** [comment]
genial ahora la bajo y pruebo
