### ISSUE TITLE
Si se instala via d-i sigue quedando el icono de calamares

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/live-cd#24]
Hay que agregar en el presed de d-i que en el comando post instalacion tambien remueva el calamares del chroot . Asi que queda una vez instalado.

**Comment by matiasdelellis** [comment]
Estuve toda la mañana desc****** esto..
En definitiva debian-installer esta preparado para borrar `calamares-settings-debian`.. entonces deberiamos usar el mismo nombre..
(Y el borrado personalizado por el archivo filesystem.packages-remove no estaria funcionando)

**Comment by ftoledo** [comment]
Otro lugar es sobre d-i preseed/late_command  cuando termina de instarlar el d-i ahi se puede agrear un apt-get remove de ese paquete y listo. Deberia funcionar.

**Comment by ftoledo** [comment]
Ya estoy desestimando la inclusion del d-i
