### ISSUE TITLE
release de huayra 4?

### ISSUE THREAD

**Issue by ImUrX** [HuayraLinux/live-cd#25]
hace tiempo escuche de este proyecto y queria ver que tanto avanzo, la pagina honestamente no es muy buena y el video instructivo del iso hace referencia a un dominio (huayra.gob.ar) que ni siquiera fue registrado en nic (quizas lo fue antes? aunque imposible xq fue publicado en enero este video)

bueno despues de todo ese testamento, acaso podrian hacer una release oficial de 4 porfa?

**Comment by ftoledo** [comment]
Estamos actulizando todo para hacer la version 5!
Saludos!
