### ISSUE TITLE
Hay que revisar el rufus incluido que no es compatible.

### ISSUE THREAD

**Issue by matiasdelellis** [HuayraLinux/live-cd#26]
@ftoledo 
Santi estuvo probando para hacer un tutorial de instalacion. y parece los dos rufus (Porque dos????) que se incluyen en la ISO, piden descargar archivos de internet..

![imagen](https://user-images.githubusercontent.com/733715/114763843-a745d380-9d39-11eb-8e17-32af7a91a9dd.png)

Justo que cambiaste el debian installer parece que cambia algo...

**Comment by ftoledo** [comment]
Seguro bajé uno nuevo en algun momento y olvidé eliminar el anterior.

El 3.13p (portable) seria el ultimo. 

Con respecto al syslinux, quizas el portable chequee contrar internet que haya version mas nueva. (lo voy a investigar)

**Comment by ftoledo** [comment]
De todas maneras creo que no deberia hacer falta que use el syslinux para copiar el .iso al pendrive. Consigo alguna maquina con windows y lo pruebo.

**Comment by matiasdelellis** [comment]
Hoy estuve probando esto...
No estoy seguro si usar syslinux o no.. pero en definitiva si pide descargar archivos, es un problema por la idea es que funcione sin internet..
Lo que podemos hacer es agregar los archivos que dascarga en la misma iso.. queda una carpera rufus_files que contiene los archivos que se corresponden a la misma iso..

**Comment by matiasdelellis** [comment]
@ftoledo 
Esta serian todos los archivos.... (Agrego el rufus.ini para que tampoco pregunte por actualizaciones)

[rufus_files.tar.gz](https://github.com/HuayraLinux/live-cd/files/6326075/rufus_files.tar.gz)

**Comment by ftoledo** [comment]
Falta verificar si con esa version de rufus queda ok

**Comment by matiasdelellis** [comment]
Justo estoy copiando el archivo para eso..

**Comment by matiasdelellis** [comment]
Perfecto.. Probado en windows 10 pelado.

1. Doble click sobre la iso y la monta..
2. Entras a d:\install\
3. ejectas rufus*exe.
4. Solocas el pen..
5. Le das comensar con todas las opciones por defecto..

Y anda perfecto sin ningun reporte de versiones y el pen resultante anda an maquinas efi y no efi..
