### ISSUE TITLE
Aún muestra debian installer..

### ISSUE THREAD

**Issue by matiasdelellis** [HuayraLinux/live-cd#29]
Entiendo que lo hace en las viejas máquinas con modo de compatibilidad..

![IMG_20210502_142638_233](https://user-images.githubusercontent.com/733715/116821918-70055e00-ab52-11eb-9be3-4657e9a0a3c5.jpg)

Eso es lo de menos si no fuera por qué dice huayra 4.. 😂

**Comment by ftoledo** [comment]
Calamares está andando bien tanto para firmware uefi como para bios, por lo tanto saco esos opciones del menu.
