### ISSUE TITLE
No se detecta la tarjeta SD en los SF20GM7 si es colocada despues de bootear

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/live-cd#30]
Si la tarjeta esta colocada antes de arrancar, el lector funciona como se espera.

Pero si se agrega la tarjeta despues de bootear, no la detecta.

adjunto dmesg con la tarjeta y sin ella

[sin.txt](https://github.com/HuayraLinux/live-cd/files/6461466/sin.txt)
[con.txt](https://github.com/HuayraLinux/live-cd/files/6461468/con.txt)

**Comment by matiasdelellis** [comment]
Este bug es solo con kernel backport, que ya no lo utilizamos mas,,
