### ISSUE TITLE
Considerar Flatpak

### ISSUE THREAD

**Issue by santiagocezar** [HuayraLinux/live-cd#35]
Actualmente, Huayra no incluye ningún centro de software amigable (estilo GNOME Software). La forma predeterminada de instalar aplicaciones es mediante "Paquetes", o descargando .DEBs de internet. [Flatpak](https://flatpak.org/) es un formato de paquetes de aplicaciones universal. Permitiría no sólo el acceso a su [gran catálogo](https://flathub.org/home) de aplicaciones, sino que también a sus últimas versiones.

Mi propuesta es que Huayra traiga Flatpak instalado, más algunas aplicaciones en formato Flatpak (Blender por ejemplo, Huayra trae una versión de 2017). Esto también facilitaría el tema de las actualizaciones de software, ya que se realizarían automáticamente por separado de las actualizaciones del sistema.

Creo que mejoraría bastante la experiencia del usuario promedio, hace poco un compañero me preguntó como instalar cierto juego de bloques en su netbook Juana Manso y tuvimos que dar varias vueltas por la Terminal hasta que pudo instalarla, de ahí surgió la necesidad de esta petición.

Sinceramente, un alumno de 7mo año que empezó a usar Linux gracias a ustedes :)

**Comment by ftoledo** [comment]
Estoy de acuerdo. yo siempre fui un poco reacio a este tipos de repos "ajenos" a las distros, no @matiasdelellis?, pero hoy por hoy son bastante estables y hay varias aplicaciones que se pueden usar tranquilamente tanto como en snap.
Podriamos agregar ambos paquetes.

**Comment by ftoledo** [comment]
Se agregó  flatpak en Huayra 6.0
