### ISSUE TITLE
error en build - repositorio incorrecto

### ISSUE THREAD

**Issue by rdcarranza** [HuayraLinux/live-cd#37]
Al realizar el build con: 

sudo ARCH=amd64 RELEASE_VERSION=6.0 EFI=1 lb build

Err:4 http://security.debian.org/debian-security bullseye/updates Release
  404  Not Found [IP: 151.101.218.132 80]
Hit:5 http://deb.debian.org/debian bullseye-updates InRelease
Hit:6 http://repo.huayra.educar.gob.ar/huayra norte-updates InRelease
Reading package lists...
E: The repository 'http://security.debian.org/debian-security bullseye/updates Release' does not have a Release file.

Este error es porque el repositorio correcto es: 'http://security.debian.org/debian-security bullseye-security/updates Release'

Pero no sé como funciona live-build en el armado de string. Veo que las variables estan en el archivo config/bootstrap pero no logro encontrar una forma para generar la dirección correcta.

La solución que estoy probando y no recomiendo: 
En el archivo config/chroot modifique la variable LB_SECURITY="false".

Saludos.

**Comment by ftoledo** [comment]
hola @rdcarranza  en que rama estabas probando? 
ahora actualice el master con huayra6

y vos el host donde estas ejecutando el live-build que version de debian estas usando? aca lo hacemos sobre un debian 11 con live-build version 1:20210407

**Comment by rdcarranza** [comment]
Hola @ftoledo estoy probando sobre la rama huayra6 (por default). En el host probé con huayra 5 y debian 10. Y en ambos casos continua el mismo error.

Voy a probar con debian 11. Gracias.

**Comment by ftoledo** [comment]
@rdcarranza dale perfecto! 
Me juego que es por la versión del live-build de debian 10 porque seguro no tiene los repos actualizados de debian 11.
quizás podes usar el de backports.. pero igual te recomiendo que el host sea 11 tambien.
abrazo!

**Comment by rdcarranza** [comment]
@ftoledo buenas!
Fue como lo dijiste, pude armar Huayra 6 con un host Debian 11.

Te agradezco mucho, saludos.
